# Generated by Django 4.2.23 on 2025-08-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('value', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('rent', 'Жилье / Аренда'), ('utilities', 'Коммунальные платежи'), ('transport', 'Транспорт'), ('communication', 'Связь'), ('health', 'Здоровье'), ('loan', 'Кредиты'), ('groceries', 'Продукты'), ('eating_out', 'Кафе и рестораны'), ('clothes', 'Одежда и обувь'), ('entertainment', 'Развлечения'), ('gifts', 'Подарки'), ('education', 'Образование'), ('beauty', 'Красота и уход'), ('other', 'Другое')], default='groceries', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('value', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('salary', 'Зарплата'), ('freelance', 'Дополнительный доход / Фриланс'), ('gift', 'Подарки'), ('investment', 'Инвестиции'), ('cashback', 'Кэшбэк'), ('other', 'Другое')], default='groceries', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
            },
        ),
    ]
